SIMULATION: # pulling baseline - prd / all expand / all remediate simulation scenarios daily + actuals
  simulation_scenario: ['baseline', 'remediation'] # 'baseline', 'remediation', 'expansion'
  lookback_day_count: 7 # if start date and end date is given, then lookback_day_count is overwritten
  start_date: null # '2025-11-01' # inclusive
  end_date: null #'2025-11-07' # inclusive


EXECUTION_DATA: # pulling unpadded dea / shutdown / backlog daily
  lookback_day_count: 14 # if start date and end date is given, then lookback_day_count is overwritten
  start_date: null # '2025-10-25' # inclusive
  end_date: null # '2025-11-08' # inclusive


EXECUTION:
  run_name: 'default'
  save_to_snowflake: False
  save_to_local: True

  expansion: False
  remediation: True

  # this dates are used to get the simulation data & define zip status based on smf
  lookback_day_count: 7 # if start date and end date is given, then lookback_day_count is overwritten
  start_date: null # '2025-11-07' # inclusive
  end_date: null #'2025-11-13' # inclusive

  baseline_scenario: 'baseline' 
  expansion_scenario: 'expansion'
  remediation_scenario: 'remediation'

  recommendation_count_list: []
  zip_volume_floor: 25
  fc_switch_threshold: 0.15

  dea_threshold: 0.9
  dea_lookback_day_count: 7

  backlog_threshold: 0.5
  clear_date_threshold: 1


PLANNING:
  run_name: 'ogunes-dev'

  expansion: True
  remediation: False

  lookback_day_count: null # if start date and end date is given, then lookback_day_count is overwritten
  start_date: '2025-10-05' # inclusive
  end_date: '2025-10-11' # inclusive

  baseline_scenario: 'baseline' 
  expansion_scenario: 'expansion'
  remediation_scenario: 'remediation'

  fc_switch_threshold: 0.1
  ontrgd_target: 0.18
  package_count_change_list: null






